/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "DATE_PROG.h"
#include <stdio.h>

long * bin_date_1_svc(void *argp, struct svc_req *rqstp) {
	static long  result;
	/*
	 * insert server code here
	 */
    printf("Bin date\n");
    long a = 404;
    result = a;
	return &result;
}

char ** str_date_1_svc(long *argp, struct svc_req *rqstp) {
	static char * result;
	/*
	 * insert server code here
	 */
    printf("Hola mundo\n");
    char a = 'a';
    result = &a;
	return &result;
}
