/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_PROG_H_RPCGEN
#define _CALC_PROG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct doublepair {
	double a;
	double b;
};
typedef struct doublepair doublepair;

#define CALC_PROG 0x31314141
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define sumar 1
extern  double * sumar_1(doublepair *, CLIENT *);
extern  double * sumar_1_svc(doublepair *, struct svc_req *);
#define multiplicar 2
extern  double * multiplicar_1(doublepair *, CLIENT *);
extern  double * multiplicar_1_svc(doublepair *, struct svc_req *);
#define dividir 3
extern  double * dividir_1(doublepair *, CLIENT *);
extern  double * dividir_1_svc(doublepair *, struct svc_req *);
#define porcentaje 4
extern  double * porcentaje_1(doublepair *, CLIENT *);
extern  double * porcentaje_1_svc(doublepair *, struct svc_req *);
#define raizCuadrada 5
extern  double * raizcuadrada_1(double *, CLIENT *);
extern  double * raizcuadrada_1_svc(double *, struct svc_req *);
#define potencia 6
extern  double * potencia_1(doublepair *, CLIENT *);
extern  double * potencia_1_svc(doublepair *, struct svc_req *);
#define reciproco 7
extern  double * reciproco_1(double *, CLIENT *);
extern  double * reciproco_1_svc(double *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sumar 1
extern  double * sumar_1();
extern  double * sumar_1_svc();
#define multiplicar 2
extern  double * multiplicar_1();
extern  double * multiplicar_1_svc();
#define dividir 3
extern  double * dividir_1();
extern  double * dividir_1_svc();
#define porcentaje 4
extern  double * porcentaje_1();
extern  double * porcentaje_1_svc();
#define raizCuadrada 5
extern  double * raizcuadrada_1();
extern  double * raizcuadrada_1_svc();
#define potencia 6
extern  double * potencia_1();
extern  double * potencia_1_svc();
#define reciproco 7
extern  double * reciproco_1();
extern  double * reciproco_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_doublepair (XDR *, doublepair*);

#else /* K&R C */
extern bool_t xdr_doublepair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_PROG_H_RPCGEN */
