/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "CALC_PROG.h"
#include <stdio.h>
#include <stdlib.h>

int menu();
int validaEntero();

void calc_prog_1(char *host, int opt) {
	CLIENT *clnt;
	double  *result_1;
	doublepair  sumar_1_arg;
	double  *result_2;
	doublepair  multiplicar_1_arg;
	double  *result_3;
	doublepair  dividir_1_arg;
	double  *result_4;
	doublepair  porcentaje_1_arg;
	double  *result_5;
	double  raizcuadrada_1_arg;
	double  *result_6;
	doublepair  potencia_1_arg;
	double  *result_7;
	double  reciproco_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    switch (opt) {
        case 1:
            printf("a: ");
            scanf("%lf", &sumar_1_arg.a);
            printf("b: ");
            scanf("%lf", &sumar_1_arg.b);
            result_1 = sumar_1(&sumar_1_arg, clnt);
            if (result_1 == (double *) NULL) {
                clnt_perror (clnt, "call failed");
            }
            printf("El resultado es %0.3lf\n", *result_1);
            break;
        case 2:
            printf("a: ");
            scanf("%lf", &multiplicar_1_arg.a);
            printf("b: ");
            scanf("%lf", &multiplicar_1_arg.b);
            result_2 = multiplicar_1(&multiplicar_1_arg, clnt);
            if (result_2 == (double *) NULL) {
                clnt_perror (clnt, "call failed");
            }
            printf("El resultado es %0.3lf\n", *result_2);
            break;
        case 3:
            printf("a: ");
            scanf("%lf", &dividir_1_arg.a);
            printf("b: ");
            scanf("%lf", &dividir_1_arg.b);
            result_3 = dividir_1(&dividir_1_arg, clnt);
            if (result_3 == (double *) NULL) {
                clnt_perror (clnt, "call failed");
            }
            printf("El resultado es %0.3lf\n", *result_3);
            break;
        case 4:
            printf("a: ");
            scanf("%lf", &porcentaje_1_arg.a);
            printf("b: ");
            scanf("%lf", &porcentaje_1_arg.b);
            result_4 = porcentaje_1(&porcentaje_1_arg, clnt);
            if (result_4 == (double *) NULL) {
                clnt_perror (clnt, "call failed");
            }
            printf("%0.2lf representa el %0.1lf%% de %0.2lf\n",porcentaje_1_arg.b, *result_4, porcentaje_1_arg.a);
            break;
        case 5:
            printf("a: ");
            scanf("%lf", &raizcuadrada_1_arg);
            result_5 = raizcuadrada_1(&raizcuadrada_1_arg, clnt);
            if (result_5 == (double *) NULL) {
                clnt_perror (clnt, "call failed");
            }
            printf("El resultado es %0.3lf\n", *result_5);
            break;
        case 6:
            printf("a: ");
            scanf("%lf", &potencia_1_arg.a);
            printf("b: ");
            scanf("%lf", &potencia_1_arg.b);
            result_6 = potencia_1(&potencia_1_arg, clnt);
            if (result_6 == (double *) NULL) {
                clnt_perror (clnt, "call failed");
            }
            printf("El resultado es %0.3lf\n", *result_6);
            break;
        case 7:
            printf("a: ");
            scanf("%lf", &reciproco_1_arg);
            result_7 = reciproco_1(&reciproco_1_arg, clnt);
            if (result_7 == (double *) NULL) {
                clnt_perror (clnt, "call failed");
            }
            printf("El resultado es %0.3lf\n", *result_7);
            break;
    }

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int menu() {
    int opt = -1;
    printf("Elije una opción:\n");
    printf("1) Sumar (a, b).\n");
    printf("2) Multiplicar (a, b).\n");
    printf("3) Dividir (a, b).\n");
    printf("4) Porcentaje (a, b).\n");
    printf("5) Raíz cuadrada (a).\n");
    printf("6) Potencia (a, b).\n");
    printf("7) Reciproco (a).\n");
    printf("8) Salir.\n>> ");
    opt = validaEntero();
    return opt;
}

int validaEntero() {
    int num, ok, ch;
    do {
		fflush(stdout);
		if ((ok = scanf("%d", &num)) == EOF)
		return EXIT_FAILURE;

		if ((ch = getchar()) != '\n') {
    		ok = 0;
    		printf("Vuelva a intentarlo: ");
    		while ((ch = getchar()) != EOF && ch != '\n');
		}
	} while(!ok);

	return num;
}

int main (int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
    int control = 1, opt;
    char aux;

    do {
        // system("cls"); // Windows
        system("clear"); // GNU/Linux
        opt = menu();
        switch (opt) {
            case 1:
                calc_prog_1 (host, 1);
                break;
            case 2:
                calc_prog_1 (host, 2);
                break;
            case 3:
                calc_prog_1 (host, 3);
                break;
            case 4:
                calc_prog_1 (host, 4);
                break;
            case 5:
                calc_prog_1 (host, 5);
                break;
            case 6:
                calc_prog_1 (host, 6);
                break;
            case 7:
                calc_prog_1 (host, 7);
                break;
            case 8:
                control = 0;
                break;
            default:
                printf("¡Opción no válida!\n");
        }
        printf("Presione una tecla para continuar...");
        aux = getchar(); aux = getchar();
    } while(control);
    if((int)aux != 0) aux = '\0';
    exit (0);
}
