/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "CALC_PROG.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

// Realiza una simple suma A + B
double * sumar_1_svc(doublepair *argp, struct svc_req *rqstp) {
	static double  result;

	result = argp->a + argp->b;
    printf("Suma\n");
	return &result;
}

// Realiza una simple multiplicación A * B
double * multiplicar_1_svc(doublepair *argp, struct svc_req *rqstp) {
	static double  result;

	result = argp->a * argp->b;
    printf("Multiplicación\n");
	return &result;
}

// Realiza un simple división A / B
double * dividir_1_svc(doublepair *argp, struct svc_req *rqstp) {
	static double  result;

	result = argp->a / argp->b;
    printf("División\n");
	return &result;
}

// Retorna el porcentaje que representa B respecto a A.
double * porcentaje_1_svc(doublepair *argp, struct svc_req *rqstp) {
	static double  result;

    result = (argp->b * 100) / argp->a;
    printf("Porcentaje\n");
	return &result;
}

// Obtiene la raíz cuadrada de un número, num ^ (1/2)
double * raizcuadrada_1_svc(double *argp, struct svc_req *rqstp) {
	static double  result;

    result = sqrt(*argp);
    printf("Raíz cuadrada\n");
	return &result;
}

// Calcula A^B
double * potencia_1_svc(doublepair *argp, struct svc_req *rqstp) {
	static double  result;

    result = pow(argp->a, argp->b);
    printf("Potencia\n");
	return &result;
}

// Calcula el inverso multiplicativo de un número
double * reciproco_1_svc(double *argp, struct svc_req *rqstp) {
	static double  result;

	result = 1 / *argp;
    printf("Reciproco\n");
	return &result;
}
